# Generated by Django 3.2.6 on 2021-10-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('gia', models.IntegerField(default=0)),
                ('giacu', models.IntegerField(default=0)),
                ('soluong', models.IntegerField(default=0)),
                ('soconlai', models.IntegerField(default=0)),
            ],
        ),
    ]
