# Generated by Django 3.2.6 on 2021-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km',
            name='soluong',
            field=models.CharField(max_length=5000),
        ),
    ]
