# Generated by Django 3.2.6 on 2021-10-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('itemsjson', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('amount', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('categogy', models.CharField(default='', max_length=50)),
                ('subcategogy', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('main', models.CharField(max_length=500)),
                ('cpu', models.CharField(max_length=500)),
                ('ram', models.CharField(max_length=500)),
                ('cardhinh', models.CharField(max_length=500)),
                ('hdd', models.CharField(max_length=500)),
                ('monitor', models.CharField(max_length=500)),
                ('madeby', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateOrder',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
